# Copyright (C) 2018 MizukiSonoko. All rights reserved.
version: 2.0
jobs:
  base:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/MizukiSonoko/goparse
    steps:

      - run:
          name: install clang
          command: sudo apt install clang

      - run:
          name: install vgo
          command: go get -u golang.org/x/vgo

      - run:
          name: install megacheck
          command: go get honnef.co/go/tools/cmd/megacheck

      - checkout

      - run:
         name: test
         command: make test

      - run:
          name: Upload reports to codecov
          command: |
            make cover
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - base
